test

diff --git a/.drone.yml b/.drone.yml
--- a/.drone.yml
+++ b/.drone.yml
@@ -39,7 +39,7 @@ environment:
 
 x-anchors:
   retrieve-aws-key: &retrieve-aws-key |
-    set -euo pipefail
+set -euo pipefail
     vault --version
 
     CREDS_JSON="$(vault read -format=json aws_dacc_dq/creds/drone)"
@@ -51,25 +51,30 @@ x-anchors:
 
     LEASE_ID="$(printf '%s' "$CREDS_JSON" | jq -r '.lease_id')"
     vault lease renew -increment=3600 "$LEASE_ID"
+
+    # Hard fail if anything is missing
+    : "${AWS_ACCESS_KEY_ID:?missing access key}"
+    : "${AWS_SECRET_ACCESS_KEY:?missing secret key}"
+    : "${AWS_SESSION_TOKEN:?missing session token}"
 
   check-format: &check-format
     - terraform --version
     - terraform fmt --diff --check
 
-  run-testrunner-tests: &run-testrunner-tests |
-    set -euo pipefail
-    vault --version
+  # run-testrunner-tests: &run-testrunner-tests |
+  #   set -euo pipefail
+  #   vault --version
 
-    CREDS_JSON="$(vault read -format=json aws_dacc_dq/creds/drone)"
+  #   CREDS_JSON="$(vault read -format=json aws_dacc_dq/creds/drone)"
 
-    export AWS_ACCESS_KEY_ID="$(printf '%s' "$CREDS_JSON" | jq -r '.data.access_key')"
-    export AWS_SECRET_ACCESS_KEY="$(printf '%s' "$CREDS_JSON" | jq -r '.data.secret_key')"
-    export AWS_SESSION_TOKEN="$(printf '%s' "$CREDS_JSON" | jq -r '.data.session_token')"
-    export AWS_DEFAULT_REGION="${AWS_REGION}"
+  #   export AWS_ACCESS_KEY_ID="$(printf '%s' "$CREDS_JSON" | jq -r '.data.access_key')"
+  #   export AWS_SECRET_ACCESS_KEY="$(printf '%s' "$CREDS_JSON" | jq -r '.data.secret_key')"
+  #   export AWS_SESSION_TOKEN="$(printf '%s' "$CREDS_JSON" | jq -r '.data.session_token')"
+  #   export AWS_DEFAULT_REGION="${AWS_REGION}"
 
-    LEASE_ID="$(printf '%s' "$CREDS_JSON" | jq -r '.lease_id')"
-    vault lease renew -increment=3600 "$LEASE_ID"
-    python -m unittest tests/*_test.py
+  #   LEASE_ID="$(printf '%s' "$CREDS_JSON" | jq -r '.lease_id')"
+  #   vault lease renew -increment=3600 "$LEASE_ID"
+  #   python -m unittest tests/*_test.py
 
 
 steps:
@@ -97,7 +102,7 @@ steps:
 - name: run-testrunner-tests
   pull: if-not-exists
   image: *testrunner-image
-  commands: *run-testrunner-tests
+  commands: *retrieve-aws-key
   environment:
     VAULT_ADDR:
       from_secret: VAULT_ADDR_NOTPROD
